### ISSUE TITLE
Fails to build with Visual Studio 2010

### ISSUE THREAD

**Issue by ethanhs** [python/typed_ast#24]
I was working on appveyor builds of mypy, and when I initially tested Python 3.3 and 3.4, which use the older Visual Studio 2010 compiler, compilation failed. It'd be great if typed_ast were to compile for Python 3.3 and 3.4 on Windows

here is the log:
```shell
$ py -3.4 setup.py install
running install
running bdist_egg
running egg_info
writing top-level names to typed_ast.egg-info\top_level.txt
writing typed_ast.egg-info\PKG-INFO
writing dependency_links to typed_ast.egg-info\dependency_links.txt
reading manifest file 'typed_ast.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'typed_ast.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
building '_ast27' extension
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Iast27/Include -IC:\Python34\include -IC:\Python34\include /Tcast27/Parser/acceler.c /Fobuild\temp.win32-3.4\Release\ast27/Parser/acceler.obj
acceler.c
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Iast27/Include -IC:\Python34\include -IC:\Python34\include /Tcast27/Parser/bitset.c /Fobuild\temp.win32-3.4\Release\ast27/Parser/bitset.obj
bitset.c
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Iast27/Include -IC:\Python34\include -IC:\Python34\include /Tcast27/Parser/grammar.c /Fobuild\temp.win32-3.4\Release\ast27/Parser/grammar.obj
grammar.c
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Iast27/Include -IC:\Python34\include -IC:\Python34\include /Tcast27/Parser/grammar1.c /Fobuild\temp.win32-3.4\Release\ast27/Parser/grammar1.obj
grammar1.c
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Iast27/Include -IC:\Python34\include -IC:\Python34\include /Tcast27/Parser/node.c /Fobuild\temp.win32-3.4\Release\ast27/Parser/node.obj
node.c
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Iast27/Include -IC:\Python34\include -IC:\Python34\include /Tcast27/Parser/parser.c /Fobuild\temp.win32-3.4\Release\ast27/Parser/parser.obj
parser.c
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Iast27/Include -IC:\Python34\include -IC:\Python34\include /Tcast27/Parser/parsetok.c /Fobuild\temp.win32-3.4\Release\ast27/Parser/parsetok.obj
parsetok.c
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Iast27/Include -IC:\Python34\include -IC:\Python34\include /Tcast27/Parser/tokenizer.c /Fobuild\temp.win32-3.4\Release\ast27/Parser/tokenizer.obj
tokenizer.c
ast27/Parser/tokenizer.c(1380) : error C2143: syntax error : missing ';' before 'const'
ast27/Parser/tokenizer.c(1381) : error C2065: 'p' : undeclared identifier
ast27/Parser/tokenizer.c(1381) : warning C4047: '=' : 'int' differs in levels of indirection from 'char *'
ast27/Parser/tokenizer.c(1382) : error C2065: 'prefix' : undeclared identifier
ast27/Parser/tokenizer.c(1382) : warning C4047: '=' : 'int' differs in levels of indirection from 'const char *'
ast27/Parser/tokenizer.c(1383) : error C2065: 'prefix' : undeclared identifier
ast27/Parser/tokenizer.c(1383) : error C2100: illegal indirection
ast27/Parser/tokenizer.c(1383) : error C2065: 'p' : undeclared identifier
ast27/Parser/tokenizer.c(1383) : warning C4047: '<' : 'int' differs in levels of indirection from 'char *'
ast27/Parser/tokenizer.c(1384) : error C2065: 'prefix' : undeclared identifier
ast27/Parser/tokenizer.c(1384) : error C2100: illegal indirection
ast27/Parser/tokenizer.c(1385) : error C2065: 'p' : undeclared identifier
ast27/Parser/tokenizer.c(1385) : error C2100: illegal indirection
ast27/Parser/tokenizer.c(1385) : error C2065: 'p' : undeclared identifier
ast27/Parser/tokenizer.c(1385) : error C2100: illegal indirection
ast27/Parser/tokenizer.c(1386) : error C2065: 'p' : undeclared identifier
ast27/Parser/tokenizer.c(1387) : error C2065: 'prefix' : undeclared identifier
ast27/Parser/tokenizer.c(1387) : error C2100: illegal indirection
ast27/Parser/tokenizer.c(1387) : error C2065: 'p' : undeclared identifier
ast27/Parser/tokenizer.c(1387) : error C2100: illegal indirection
ast27/Parser/tokenizer.c(1388) : error C2065: 'p' : undeclared identifier
ast27/Parser/tokenizer.c(1393) : error C2065: 'prefix' : undeclared identifier
ast27/Parser/tokenizer.c(1397) : error C2065: 'prefix' : undeclared identifier
ast27/Parser/tokenizer.c(1397) : error C2100: illegal indirection
ast27/Parser/tokenizer.c(1401) : error C2065: 'type_start' : undeclared identifier
ast27/Parser/tokenizer.c(1401) : error C2065: 'p' : undeclared identifier
ast27/Parser/tokenizer.c(1403) : error C2065: 'p' : undeclared identifier
ast27/Parser/tokenizer.c(1403) : warning C4047: '>=' : 'char *' differs in levels of indirection from 'int'
ast27/Parser/tokenizer.c(1403) : error C2065: 'p' : undeclared identifier
ast27/Parser/tokenizer.c(1403) : warning C4022: 'memcmp' : pointer mismatch for actual parameter 1
ast27/Parser/tokenizer.c(1404) : error C2065: 'p' : undeclared identifier
ast27/Parser/tokenizer.c(1405) : error C2065: 'p' : undeclared identifier
ast27/Parser/tokenizer.c(1405) : warning C4047: '<' : 'int' differs in levels of indirection from 'char *'
ast27/Parser/tokenizer.c(1406) : error C2065: 'p' : undeclared identifier
ast27/Parser/tokenizer.c(1406) : error C2100: illegal indirection
ast27/Parser/tokenizer.c(1408) : error C2065: 'p' : undeclared identifier
ast27/Parser/tokenizer.c(1408) : error C2100: illegal indirection
ast27/Parser/tokenizer.c(1408) : error C2065: 'p' : undeclared identifier
ast27/Parser/tokenizer.c(1408) : error C2100: illegal indirection
ast27/Parser/tokenizer.c(1409) : error C2065: 'p' : undeclared identifier
ast27/Parser/tokenizer.c(1420) : error C2065: 'type_start' : undeclared identifier
```

**Comment by ddfisher** [comment]
For now, typed_ast only supports Windows for Python 3.5+, and there are no concrete plans to change this.

**Comment by ethanhs** [comment]
No problem. Just wanted to share that it is an issue.

**Comment by ddfisher** [comment]
Closing as wontfix.

**Comment by pa-eidam** [comment]
@ethanhs For your information: I'm working with Python 3.4 under Windows (WinPython-32bit-3.4.4.5Qt5). Mingwpy (my version: 0.1.0b3) is able to compile type_ast.

**Comment by ethanhs** [comment]
@pa-eidam, thanks, I was mostly just testing, but thanks for sharing a possible workaround

**Comment by ethanhs** [comment]
This was fixed in https://github.com/python/typed_ast/pull/47.
